### ISSUE TITLE
Grab files from the FTP server. / Implement user home page.

### ISSUE THREAD

**Issue by zacharyedwardsdowns** [Remedee/Skopos-Security#19]
Once the FTP server is set up implement a system for the website to grab files from it. This should also include downloading and deleting files from the server and implementing these videos on a user's home page. Thus this issue will include ~~finalizing the look of a user's user page home page and~~ allowing for the downloading and deletion of videos from it.
(User homepage UI made it's own issue.)

**Comment by Remedee** [comment]
This should also include downloading and deleting files from the server and implementing these videos on a user's page.
